import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "./common/components/theme-provider";
import Navbar from "./common/components/navbar";
import "./globals.css";
import ServiceWorkerRegister from "./common/components/serviceworker-register";
import type { Viewport } from "next";
import OnlineContextProvider from "./common/components/hooks/online-provider";
import Alert from "./common/components/alert";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ServiceWorkerRegister />
        <Alert>
          <OnlineContextProvider>
            <ThemeProvider>
              <Navbar />
              {children}
            </ThemeProvider>
          </OnlineContextProvider>
        </Alert>
      </body>
    </html>
  );
}
